import * as core from '@actions/core';
import * as github from '@actions/github';
import OpenAI from 'openai';

const MAX_DIFF_CHARS = 8000;

interface PullRequestContext {
  owner: string;
  repo: string;
  pullNumber: number;
}

function getInputs(): { openaiApiKey: string; githubToken: string } {
  const openaiApiKey = core.getInput('openai-api-key', { required: true });
  const githubToken = core.getInput('github-token', { required: true });
  return { openaiApiKey, githubToken };
}

function getPullRequestContext(): PullRequestContext {
  const payload = github.context.payload;
  const pullRequest = payload.pull_request;

  if (!pullRequest) {
    throw new Error(
      'This action must be triggered by a pull_request event (opened or synchronize).'
    );
  }

  const owner = github.context.repo.owner;
  const repo = github.context.repo.repo;
  const pullNumber = pullRequest.number;

  if (!owner || !repo || !pullNumber) {
    throw new Error(
      `Unable to determine PR context. owner=${owner}, repo=${repo}, pullNumber=${pullNumber}`
    );
  }

  return { owner, repo, pullNumber };
}

async function fetchPullRequestDiff(
  octokit: ReturnType<typeof github.getOctokit>,
  context: PullRequestContext
): Promise<string> {
  core.info(
    `Fetching diff for PR #${context.pullNumber} in ${context.owner}/${context.repo}...`
  );

  const response = await octokit.rest.pulls.get({
    owner: context.owner,
    repo: context.repo,
    pull_number: context.pullNumber,
    mediaType: {
      format: 'diff' as const,
    },
  });

  const diff = response.data as unknown as string;

  if (typeof diff !== 'string') {
    throw new Error(
      `Expected diff response to be a string, but received ${typeof diff}.`
    );
  }

  core.info(`Fetched diff length: ${diff.length} characters.`);
  return diff;
}

function truncateDiff(diff: string): string {
  if (diff.length <= MAX_DIFF_CHARS) {
    return diff;
  }

  const truncated = diff.slice(0, MAX_DIFF_CHARS);
  const truncationNotice =
    '\n\n_...diff truncated due to token limit; showing first 8,000 characters._';
  return truncated + truncationNotice;
}

function buildSystemPrompt(): string {
  return `You are a senior software engineer reviewing a pull request.
Please summarize the provided git diff in a clear, structured, and developer-friendly way.
Use the following Markdown format exactly:

## Summary
Provide a high-level overview of what the PR does in 2-4 sentences.

## Key Changes
- Bullet list of the most important changes.
- Focus on new files, modified logic, refactored functions, and API/contract changes.

## Impact / Risks
- Highlight potential risks, backward-incompatibility, or areas that deserve extra review.
- Mention any obvious missing tests or edge cases if applicable.

Be concise but thorough. Avoid repeating obvious filename changes unless meaningful. If the diff is empty or trivial, state that clearly.`;
}

async function summarizeDiffWithOpenAI(
  openai: OpenAI,
  diff: string
): Promise<string> {
  core.info('Sending diff to OpenAI for summarization...');

  const response = await openai.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      { role: 'system', content: buildSystemPrompt() },
      {
        role: 'user',
        content: `Here is the pull request diff:\n\n\`\`\`diff\n${diff}\n\`\`\``,
      },
    ],
    temperature: 0.2,
    max_tokens: 1500,
  });

  const summary = response.choices[0]?.message?.content?.trim();

  if (!summary) {
    throw new Error('OpenAI returned an empty summary.');
  }

  core.info('Summary generated successfully.');
  return summary;
}

async function postCommentOnPullRequest(
  octokit: ReturnType<typeof github.getOctokit>,
  context: PullRequestContext,
  body: string
): Promise<void> {
  core.info(`Posting summary comment on PR #${context.pullNumber}...`);

  await octokit.rest.issues.createComment({
    owner: context.owner,
    repo: context.repo,
    issue_number: context.pullNumber,
    body,
  });

  core.info('Comment posted successfully.');
}

async function run(): Promise<void> {
  try {
    const { openaiApiKey, githubToken } = getInputs();
    const context = getPullRequestContext();

    const octokit = github.getOctokit(githubToken);
    const openai = new OpenAI({ apiKey: openaiApiKey });

    const rawDiff = await fetchPullRequestDiff(octokit, context);

    if (rawDiff.length === 0) {
      core.info('Pull request diff is empty; nothing to summarize.');
      return;
    }

    const diff = truncateDiff(rawDiff);
    const summary = await summarizeDiffWithOpenAI(openai, diff);
    const commentBody = `## AI PR Summary\n\n${summary}\n\n---\n_Generated by ai-pr-summarizer using gpt-4o-mini._`;

    await postCommentOnPullRequest(octokit, context, commentBody);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    core.setFailed(`ai-pr-summarizer failed: ${message}`);
  }
}

run();
